name: Go CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.2' 

    - name: Check Formatting
      run: |
        test -z "$(gofmt -l -s .)" || (echo "Go code is not formatted:" && gofmt -d . && exit 1)


    - name: Lint Code
      uses: golangci/golangci-lint-action@v4
      with:
        version: latest 
        args: --timeout=5m 

    - name: Run Tests
      run: go test -v ./...

    - name: Build
      run: go build -v ./...
